//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18444
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此原始程式碼由 xsd 版本=4.0.30319.33440 自動產生。
// 
namespace TestPlanLib.Static {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/NeedSheetsConfig.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/NeedSheetsConfig.xsd", IsNullable=false)]
    public partial class NeedSheetItem {
        
        private string itemNameField;
        
        private string sheetNameField;

        private string UseNewBistField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SheetName {
            get {
                return this.sheetNameField;
            }
            set {
                this.sheetNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UseNewBist
        {
            get
            {
                return this.UseNewBistField;
            }
            set
            {
                this.UseNewBistField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/NeedSheetsConfig.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/NeedSheetsConfig.xsd", IsNullable=false)]
    public partial class NeedSheetsConfig {
        
        private NeedSheetItem[] testPlanField;
        
        private NeedSheetItem[] scghField;
        
        private NeedSheetItem[] binCutWorkBookField;

        private NeedSheetItem[] binCutPostWorkBookField;
        
        private NeedSheetItem[] nwireRelayField;
        
        private NeedSheetItem[] ioMappingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("NeedSheetItem", IsNullable=false)]
        public NeedSheetItem[] TestPlan {
            get {
                return this.testPlanField;
            }
            set {
                this.testPlanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("NeedSheetItem", IsNullable=false)]
        public NeedSheetItem[] Scgh {
            get {
                return this.scghField;
            }
            set {
                this.scghField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("NeedSheetItem", IsNullable=false)]
        public NeedSheetItem[] BinCutWorkBook {
            get {
                return this.binCutWorkBookField;
            }
            set {
                this.binCutWorkBookField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("NeedSheetItem", IsNullable = false)]
        public NeedSheetItem[] BinCutPostWorkbook
        {
            get
            {
                return this.binCutPostWorkBookField;
            }
            set
            {
                this.binCutPostWorkBookField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("NeedSheetItem", IsNullable=false)]
        public NeedSheetItem[] NwireRelay {
            get {
                return this.nwireRelayField;
            }
            set {
                this.nwireRelayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("NeedSheetItem", IsNullable=false)]
        public NeedSheetItem[] IoMapping {
            get {
                return this.ioMappingField;
            }
            set {
                this.ioMappingField = value;
            }
        }
    }
}
