//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RF_PatternTool.Template.ProximaTC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tempate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tempate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RF_PatternTool.Template.ProximaTC.Tempate", typeof(Tempate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vm_vector body ($tset JTAG_TCK, JTAG_TDI, JTAG_TMS, JTAG_SEL, CFSB,
        /// JTAG_TRSTN, TESTMODE, RESETN, JTAG_TDO, EPA_MODE_0_1, GPIO0, PERST, (GPIO1,
        /// GPIO7, GPIO6, GPIO5, GPIO4, GPIO3, GPIO2), TST_CLK_PMGR, QSPI_CSN,
        /// (EPA_MODE_1_0, EPA_MODE_1_1), (CMD_CMPLT_PULSE_IND_B_0,
        /// CMD_CMPLT_PULSE_IND_B_1, CMD_CMPLT_PULSE_IND_B_2, CMD_CMPLT_PULSE_IND_B_3),
        /// SPI_CK, SPI_CSN, (SPI_DATA0, SPI_DATA1, SPI_DATA2, SPI_DATA3, SPI_DATA4,
        /// SPI_DATA5, SPI_DATA6, SPI_DATA7), (AGC_GAIN_WORD0_6, AGC_GAIN_WORD0_5,
        /// AGC_GAIN_WO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProximaTCBody {
            get {
                return ResourceManager.GetString("ProximaTCBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srm_vector name ($tset JTAG_TCK, JTAG_TDI, JTAG_TMS, JTAG_SEL, CFSB,
        /// JTAG_TRSTN, TESTMODE, RESETN, JTAG_TDO, EPA_MODE_0_1, GPIO0, PERST, (GPIO1,
        /// GPIO7, GPIO6, GPIO5, GPIO4, GPIO3, GPIO2), TST_CLK_PMGR, QSPI_CSN,
        /// (EPA_MODE_1_0, EPA_MODE_1_1), (CMD_CMPLT_PULSE_IND_B_0,
        /// CMD_CMPLT_PULSE_IND_B_1, CMD_CMPLT_PULSE_IND_B_2, CMD_CMPLT_PULSE_IND_B_3),
        /// SPI_CK, SPI_CSN, (SPI_DATA0, SPI_DATA1, SPI_DATA2, SPI_DATA3, SPI_DATA4,
        /// SPI_DATA5, SPI_DATA6, SPI_DATA7), (AGC_GAIN_WORD0_6, AGC_GAIN_WORD0_5,
        /// AGC_GAIN_W [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProximaTCMatchLoop {
            get {
                return ResourceManager.GetString("ProximaTCMatchLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; tsetJTAG 1 0 0 1 1 1 1 1 X X 0 0 0XXXX00 X X XX XXXX X X XXXXXXXX XXXXXXX X XXXXXXX X X XXXX X XXX X XXXX X XXX X X X X X X XX XXXX X XXXX X XXXXX X XXX X X XX XXXXX X X X X X XX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XX XXXX XXX XX X X X XXXX XXXX X X X X X X X XX XX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X X X X XX X XXX XXXXX X XX X X X X X XXX X X ; // 6250 V:150 C:151 
        /// &gt; tsetJTAG 1 0 1 1 1 1 1 1 X X 0 0 0XXXX00 X X XX XXXX X X XXXXXXXX XXXXXXX X XXXXXXX X X XXXX X XXX X XXXX X XXX X X X X X X [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProximaTCRead {
            get {
                return ResourceManager.GetString("ProximaTCRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srm_vector name ($tset JTAG_TCK, JTAG_TDI, JTAG_TMS, JTAG_SEL, CFSB,
        /// JTAG_TRSTN, TESTMODE, RESETN, JTAG_TDO, EPA_MODE_0_1, GPIO0, PERST, (GPIO1,
        /// GPIO7, GPIO6, GPIO5, GPIO4, GPIO3, GPIO2), TST_CLK_PMGR, QSPI_CSN,
        /// (EPA_MODE_1_0, EPA_MODE_1_1), (CMD_CMPLT_PULSE_IND_B_0,
        /// CMD_CMPLT_PULSE_IND_B_1, CMD_CMPLT_PULSE_IND_B_2, CMD_CMPLT_PULSE_IND_B_3),
        /// SPI_CK, SPI_CSN, (SPI_DATA0, SPI_DATA1, SPI_DATA2, SPI_DATA3, SPI_DATA4,
        /// SPI_DATA5, SPI_DATA6, SPI_DATA7), (AGC_GAIN_WORD0_6, AGC_GAIN_WORD0_5,
        /// AGC_GAIN_W [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProximaTCSub {
            get {
                return ResourceManager.GetString("ProximaTCSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; tsetJTAG 1 0 0 1 1 1 1 1 X X 0 0 0XXXX00 X X XX XXXX X X XXXXXXXX XXXXXXX X XXXXXXX X X XXXX X XXX X XXXX X XXX X X X X X X XX XXXX X XXXX X XXXXX X XXX X X XX XXXXX X X X X X XX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XX XXXX XXX XX X X X XXXX XXXX X X X X X X X XX XX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X X X X XX X XXX XXXXX X XX X X X X X XXX X X ; // 6250 V:150 C:151 
        /// &gt; tsetJTAG 1 0 1 1 1 1 1 1 X X 0 0 0XXXX00 X X XX XXXX X X XXXXXXXX XXXXXXX X XXXXXXX X X XXXX X XXX X XXXX X XXX X X X X X X [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProximaTCWrite {
            get {
                return ResourceManager.GetString("ProximaTCWrite", resourceCulture);
            }
        }
    }
}
