<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TerLintAnalyzer\TerLintAnalyzer.csproj" PrivateAssets="all" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="5.3.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonLib\CommonLib.csproj" />
  </ItemGroup>

</Project>