<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<OutputType>Library</OutputType>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Nullable>enable</Nullable>
	</PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TestPlanLib.Test" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TerLintAnalyzer\TerLintAnalyzer.csproj" PrivateAssets="all" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="EPPlus" Version="4.5.3.2" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Static\NeedSheetsConfig.cs">
			<DependentUpon>NeedSheetsConfig.xsd</DependentUpon>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<None Include="Static\NeedSheetsConfig.xsd">
			<SubType>Designer</SubType>
		</None>
	</ItemGroup>
	<ItemGroup>
		<Content Include="Settings\Basic\NeedSheetConfig_Default.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CommonLib\CommonLib.csproj" />
		<ProjectReference Include="..\CommonReaderLib\CommonReaderLib.csproj" />
		<ProjectReference Include="..\IgxlLib\IgxlLib.csproj" />
		<ProjectReference Include="..\LogLib\LogLib.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Vre\" />
	</ItemGroup>

</Project>