<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<TestProjectType>UnitTest</TestProjectType>
		<IsTestProject>true</IsTestProject>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MSTest" Version="4.4.0" />
		<PackageReference Include="coverlet.collector" Version="6.0.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CommonLib\CommonLib.csproj" />
	</ItemGroup>

</Project>