<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<OutputType>Library</OutputType>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CSharp" Version="4.*" />
		<PackageReference Include="EPPlus" Version="4.5.3.2" />
		<PackageReference Include="ExcelDna.Interop" Version="15.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="NLog" Version="5.3.4" />
		<PackageReference Include="System.Security.Permissions" Version="8.0.0" />
	</ItemGroup>

</Project>