<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <!--<ItemGroup>
    <ProjectReference Include="..\Common\TerLintAnalyzer\TerLintAnalyzer.csproj" PrivateAssets="all" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>-->

  <ItemGroup>
    <Folder Include="Utility\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Automation\Automation.csproj" />
    <ProjectReference Include="..\Common\CommonLib\CommonLib.csproj" />
    <ProjectReference Include="..\Common\IgxlLib\IgxlLib.csproj" />
    <ProjectReference Include="..\Common\MyCommandLineLib\MyCommandLineLib.csproj" />
    <PackageReference Include="EPPlus" Version="4.5.3.2" />
    <PackageReference Include="Ionic.Zip" Version="1.9.1.8" />
    <PackageReference Include="Teradyne.Oasis.IGData" Version="4.0.0">
      <NoWarn>NU1701</NoWarn>
    </PackageReference>
    <PackageReference Include="Teradyne.Oasis.IGLinkBase" Version="4.0.0">
      <NoWarn>NU1701</NoWarn>
    </PackageReference>
    <PackageReference Include="Teradyne.Oasis.OasisUtilityLib" Version="4.0.0">
      <NoWarn>NU1701</NoWarn>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
