//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Teradyne.Oasis.IGData.Utilities/IGXL.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://Teradyne.Oasis.IGData.Utilities/IGXL.xsd", IsNullable=false)]
public partial class IGXL {
    
    private SheetObjMap[] sheetItemClassField;
    
    private string versionField;
    
    private bool orderedField;
    
    public IGXL() {
        this.orderedField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SheetItemClass")]
    public SheetObjMap[] SheetItemClass {
        get {
            return this.sheetItemClassField;
        }
        set {
            this.sheetItemClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool ordered {
        get {
            return this.orderedField;
        }
        set {
            this.orderedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Teradyne.Oasis.IGData.Utilities/IGXL.xsd")]
public partial class SheetObjMap {
    
    private SheetField[] fieldField;
    
    private ClassSequenceProperty sequencePropertyField;
    
    private ClassInnerObj[] innerObjField;
    
    private string sheetnameField;
    
    private string sheetversionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Field")]
    public SheetField[] Field {
        get {
            return this.fieldField;
        }
        set {
            this.fieldField = value;
        }
    }
    
    /// <remarks/>
    public ClassSequenceProperty SequenceProperty {
        get {
            return this.sequencePropertyField;
        }
        set {
            this.sequencePropertyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("InnerObj")]
    public ClassInnerObj[] InnerObj {
        get {
            return this.innerObjField;
        }
        set {
            this.innerObjField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sheetname {
        get {
            return this.sheetnameField;
        }
        set {
            this.sheetnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sheetversion {
        get {
            return this.sheetversionField;
        }
        set {
            this.sheetversionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Teradyne.Oasis.IGData.Utilities/IGXL.xsd")]
public partial class SheetField {
    
    private string fieldNameField;
    
    private int rowIndexField;
    
    private int columnIndexField;
    
    private string nameInSheetField;
    
    private string defaultValueField;
    
    public SheetField() {
        this.defaultValueField = " ";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fieldName {
        get {
            return this.fieldNameField;
        }
        set {
            this.fieldNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int rowIndex {
        get {
            return this.rowIndexField;
        }
        set {
            this.rowIndexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int columnIndex {
        get {
            return this.columnIndexField;
        }
        set {
            this.columnIndexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nameInSheet {
        get {
            return this.nameInSheetField;
        }
        set {
            this.nameInSheetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(" ")]
    public string defaultValue {
        get {
            return this.defaultValueField;
        }
        set {
            this.defaultValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Teradyne.Oasis.IGData.Utilities/IGXL.xsd")]
public partial class ClassProperty {
    
    private string nameField;
    
    private bool isRelativeField;
    
    private string relativePropertyNameField;
    
    private ClassPropertyType typeField;
    
    private int indexInSheetField;
    
    private string nameInSheetField;
    
    private bool isGroupKeyField;
    
    private bool isEmptyRowJudgeKeyField;
    
    public ClassProperty() {
        this.isRelativeField = false;
        this.indexInSheetField = 0;
        this.isGroupKeyField = false;
        this.isEmptyRowJudgeKeyField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool isRelative {
        get {
            return this.isRelativeField;
        }
        set {
            this.isRelativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string relativePropertyName {
        get {
            return this.relativePropertyNameField;
        }
        set {
            this.relativePropertyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ClassPropertyType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int indexInSheet {
        get {
            return this.indexInSheetField;
        }
        set {
            this.indexInSheetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nameInSheet {
        get {
            return this.nameInSheetField;
        }
        set {
            this.nameInSheetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool isGroupKey {
        get {
            return this.isGroupKeyField;
        }
        set {
            this.isGroupKeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool isEmptyRowJudgeKey {
        get {
            return this.isEmptyRowJudgeKeyField;
        }
        set {
            this.isEmptyRowJudgeKeyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Teradyne.Oasis.IGData.Utilities/IGXL.xsd")]
public enum ClassPropertyType {
    
    /// <remarks/>
    String,
    
    /// <remarks/>
    Long,
    
    /// <remarks/>
    Int,
    
    /// <remarks/>
    Short,
    
    /// <remarks/>
    Double,
    
    /// <remarks/>
    Float,
    
    /// <remarks/>
    List,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Teradyne.Oasis.IGData.Utilities/IGXL.xsd")]
public partial class ClassInnerObj {
    
    private ClassProperty[] propertyField;
    
    private ClassInnerObj[] innerObjComplexField;
    
    private string nameField;
    
    private string typeField;
    
    private string fullTypeField;
    
    private bool isMultiRowField;
    
    private bool isVariantField;
    
    private bool isRelativeField;
    
    private string relativePropertyNameField;
    
    public ClassInnerObj() {
        this.isMultiRowField = false;
        this.isVariantField = false;
        this.isRelativeField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Property")]
    public ClassProperty[] Property {
        get {
            return this.propertyField;
        }
        set {
            this.propertyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("InnerObjComplex")]
    public ClassInnerObj[] InnerObjComplex {
        get {
            return this.innerObjComplexField;
        }
        set {
            this.innerObjComplexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fullType {
        get {
            return this.fullTypeField;
        }
        set {
            this.fullTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool isMultiRow {
        get {
            return this.isMultiRowField;
        }
        set {
            this.isMultiRowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool isVariant {
        get {
            return this.isVariantField;
        }
        set {
            this.isVariantField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool isRelative {
        get {
            return this.isRelativeField;
        }
        set {
            this.isRelativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string relativePropertyName {
        get {
            return this.relativePropertyNameField;
        }
        set {
            this.relativePropertyNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Teradyne.Oasis.IGData.Utilities/IGXL.xsd")]
public partial class ClassSequenceProperty {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}
