using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

using Automation.Static;

using CommonLib.Enums;

using LogLib.Static;
using LogLib.Utility;

namespace Automation.Utility.Pattern
{
    public class UpdateHardIpInfo
    {
        private const string Version = "V0.2";
        private readonly string _outputFolder = Path.Combine(LocalSpecs.SettingFolder, "Settings", "HardIP") + Path.DirectorySeparatorChar;
        private readonly string _projectName;
        private readonly string _hardipFolder;
        private Dictionary<string, Tuple<string, string>> _fullPatNameTimeSetDict;
        public string OutputPath;
        private static readonly Regex _regexDssc = new Regex(@"(?<dssc>(?<bit>\d+):(?<reg>.*))", RegexOptions.IgnoreCase | RegexOptions.Compiled);

        public UpdateHardIpInfo(string projectName)
        {
            _projectName = projectName;
            _hardipFolder = LocalSpecs.PatternFolder + Path.DirectorySeparatorChar;
            OutputPath = "";
        }

        public void UpdateHardIP_Info(Dictionary<string, Tuple<string, string>> lfullPatNameTimeSetDict, string patListFileName)
        {
            _fullPatNameTimeSetDict = lfullPatNameTimeSetDict;
            var hardIpInfoAllDict = new Dictionary<string, Dictionary<string, string>>();
            string path = _hardipFolder;
            if (!string.IsNullOrEmpty(LocalSpecs.HardIpInfoFileName))
            {
                path = LocalSpecs.HardIpInfoFileName;
            }

            var hardIpAllFile = new List<string>();
            if (!File.Exists(path))
            {
                Response.Report(path + " Not Found", EnumMessageLevel.Error, 100);
                Response.Report("Try to find path : " + Path.GetDirectoryName(path), EnumMessageLevel.Error, 100);
                if (Directory.Exists(Path.GetDirectoryName(path)))
                {
                    hardIpAllFile = Directory.GetFiles(Path.GetDirectoryName(path), "*hardip*", SearchOption.AllDirectories).ToList();
                }
            }
            else
            {
                hardIpAllFile = new List<string> { path };
            }
            // Generate HardIP_PatInfo_Fiji.log
            OutputPath = _outputFolder + "HardIP_PatInfo_" + _projectName + ".log";
            if (hardIpAllFile.Any())
            {
                foreach (string file in hardIpAllFile)
                {
                    if (File.Exists(file))
                    {
                        Dictionary<string, Dictionary<string, string>> tmphardIpInfoAllDict = ReadHardIpInfoAll(file);
                        foreach (KeyValuePair<string, Dictionary<string, string>> itemDic in tmphardIpInfoAllDict)
                        {
                            if (!hardIpInfoAllDict.ContainsKey(itemDic.Key))
                            {
                                hardIpInfoAllDict.Add(itemDic.Key, new Dictionary<string, string>());
                            }

                            foreach (KeyValuePair<string, string> item in itemDic.Value)
                            {

                                if (!hardIpInfoAllDict[itemDic.Key].ContainsKey(item.Key))
                                {
                                    hardIpInfoAllDict[itemDic.Key].Add(item.Key, item.Value);
                                }
                                //Need to confirm why different file contains same version
                            }

                        }
                    }
                    else
                    {
                        Response.Report("HardIP_AutoGen_Info_All.txt Not Found in " + _hardipFolder, EnumMessageLevel.Error, 100);
                        Response.Report("HardIP_PatInfo_" + _projectName + ".log Not be updated", EnumMessageLevel.Error, 100);
                        return;
                    }
                }
                GenerateHardIP_PatInfo(_fullPatNameTimeSetDict, hardIpInfoAllDict, OutputPath, patListFileName);
            }

            Response.Report(_outputFolder + "HardIP_PatInfo_" + _projectName + ".log", EnumMessageLevel.Result, 100);
        }

        private void GenerateHardIP_PatInfo(Dictionary<string, Tuple<string, string>> fullPatNameTimeSetDict, Dictionary<string, Dictionary<string, string>> hardIpInfoAllDict, string outputPath, string patternListFile)
        {
            int count = 1;
            var builderList = new List<StringBuilder>();
            var updateStr = new StringBuilder();
            updateStr.AppendLine("############################################################################################################");
            updateStr.AppendLine("## " + patternListFile);
            updateStr.AppendLine("## Generated By Hard_IP Auto Gen_Core " + Version);
            updateStr.AppendLine("############################################################################################################");

            foreach (string fullPatName in fullPatNameTimeSetDict.Keys)
            {
                string genericPatName = GetGenericPatName(fullPatName);
                string patVersionInDashBoard = GetVersion(fullPatName);
                if (hardIpInfoAllDict.ContainsKey(genericPatName))
                {
                    foreach (string patVerStr in hardIpInfoAllDict[genericPatName].Keys)
                    {
                        string patVer = GetVersion(patVerStr);
                        if (!LocalSpecs.SearchValidPatternRev && patVer != patVersionInDashBoard)
                        {
                            continue;
                        }

                        if (patVer == patVersionInDashBoard)
                        {
                            string latestPatternVerison = GetLatestPatternVersion(hardIpInfoAllDict[genericPatName]);
                            if (latestPatternVerison != patVersionInDashBoard)
                            {
                                Response.Report(genericPatName + " ,used version: " + patVersionInDashBoard + " ,latest version: " + latestPatternVerison, EnumMessageLevel.Warning, 100, "");
                            }
                        }
                        string tempUpdateStr = hardIpInfoAllDict[genericPatName][patVerStr];
                        tempUpdateStr = tempUpdateStr.Replace("1)===", count + ")===");
                        tempUpdateStr = tempUpdateStr.Replace("Tset: NA", "Tset: " + fullPatNameTimeSetDict[fullPatName].Item2);
                        updateStr.AppendLine(tempUpdateStr);
                        count++;
                    }
                }
                if (updateStr.Length >= 1000000)
                {
                    builderList.Add(updateStr);
                    updateStr = new StringBuilder();
                }
            }
            builderList.Add(updateStr);

            UpdateFileSafely(outputPath, builderList);
        }

        internal Dictionary<string, Dictionary<string, string>> ReadHardIpInfoAll(string hardIpAllFile)
        {
            var hardIpInfoAll = new Dictionary<string, Dictionary<string, string>>();
            StreamReader sr;
            if (File.Exists(hardIpAllFile))
            {
                sr = new StreamReader(hardIpAllFile);
            }
            else
            {
                ErrorMessageBox.Show($"Missing file {hardIpAllFile} and backup file!");
                return hardIpInfoAll;
            }

            string genericPatName = string.Empty;
            string version = string.Empty;
            string hardipInfo = string.Empty;
            while (!sr.EndOfStream)
            {
                string line = sr.ReadLine()?.Trim();
                if (string.IsNullOrEmpty(line))
                {
                    continue;
                }

                if (line.StartsWith("GenericPat:="))
                {
                    genericPatName = ExtractValue(line);
                }
                else if (line.StartsWith("Version:="))
                {
                    version = ExtractValue(line);
                }
                else if (line.StartsWith("<HardIP_Info_Token>"))
                {
                    hardipInfo += "Version:" + version;
                    if (!hardIpInfoAll.ContainsKey(genericPatName))
                    {
                        Dictionary<string, string> verInfo = new Dictionary<string, string> { { version, hardipInfo } };
                        hardIpInfoAll.Add(genericPatName, verInfo);
                    }
                    // existed generic Pat new Version
                    else
                    {
                        if (!hardIpInfoAll[genericPatName].ContainsKey(version))
                        {
                            hardIpInfoAll[genericPatName].Add(version, hardipInfo);
                        }
                    }
                    // Reset state
                    genericPatName = string.Empty;
                    version = string.Empty;
                    hardipInfo = string.Empty;
                }
                else
                {
                    // Special handling for DSSC_OUT lines
                    if (LocalSpecs.Options.Device != EnumDevice.LCD && line.Contains("DSSC_OUT,"))
                    {
                        line = $"DSSC_OUT,{SplitDsscBy24(line)}";
                    }
                    hardipInfo += line + "\r\n";
                }
            }
            sr.Close();

            if (!hardIpInfoAll.Any())
            {
                Response.Report(
                    $"\n********* {hardIpAllFile} is Empty. *********" +
                    $"\n********* {hardIpAllFile} is Empty. *********" +
                    $"\n********* {hardIpAllFile} is Empty. *********" +
                    $"\n********* {hardIpAllFile} is Empty. *********" +
                    $"\n********* {hardIpAllFile} is Empty. *********" +
                    $"\n********* {hardIpAllFile} is Empty. *********",
                    EnumMessageLevel.Error, 100);
            }

            return hardIpInfoAll;
        }

        private string ExtractValue(string line)
        {
            int index = line.IndexOf(":=", StringComparison.Ordinal);
            return index >= 0 ? line.Substring(index + 2).Trim().ToUpper() : string.Empty;
        }

        public static string SplitDsscBy24(string dsscOutLine)
        {
            var modDssc = new List<string>();
            foreach (string dsscOut in dsscOutLine.Split(',').ToList())
            {
                foreach (Match m in _regexDssc.Matches(dsscOut))
                {
                    int bits = Convert.ToInt32(m.Groups["bit"].Value);
                    if (bits > 24)
                    {
                        int quotient = bits / 16;
                        int reminder = bits - (16 * quotient);
                        for (int i = 1; i <= quotient; i++)
                        {
                            string tempdssc = "16:" + m.Groups["reg"].Value + "_" + i;
                            modDssc.Add(tempdssc);
                        }
                        quotient++;

                        if (reminder != 0)
                        {
                            string reminderdssc = reminder + ":" + m.Groups["reg"].Value + "_" + quotient;
                            modDssc.Add(reminderdssc);
                        }
                    }
                    else
                    {
                        modDssc.Add(m.Groups["dssc"].Value);
                    }
                }
            }
            return string.Join(",", modDssc);
        }

        private bool CheckFileExist(string filePath)
        {
            try
            {
                if (!Directory.Exists(filePath))
                {
                    Directory.CreateDirectory(Path.GetDirectoryName(filePath));
                }

                if (File.Exists(filePath))
                { return true; }

                File.Create(filePath).Close();
                return false;
            }
            catch (Exception ex)
            {
                ErrorMessageBox.Show(string.Format(ex.ToString()));
                return false;
            }
        }

        private void UpdateFileSafely(string filePath, IEnumerable<StringBuilder> builderList)
        {
            CheckFileExist(filePath);

            // Copy file to file.tmp
            string tempFilePath = Path.ChangeExtension(filePath, ".tmp");
            if (File.Exists(tempFilePath))
            {
                File.Delete(tempFilePath);
            }

            // create and write tmp file
            FileStream fileStream = File.Create(tempFilePath);
            var streamWriter = new StreamWriter(fileStream);
            foreach (StringBuilder writeLines in builderList)
            {
                fileStream.Seek(0, SeekOrigin.End);
                streamWriter.WriteLine(writeLines);
            }
            streamWriter.Close();
            fileStream.Close();
            File.Delete(filePath);

            // Rename .tmp file to the original file
            File.Move(tempFilePath, filePath);
        }

        private string GetGenericPatName(string fullPatternName)
        {
            // fullPatternName: "D:\\HardIP_Info\\miner\\PP_MINA0_A_FULP_AN_AA03_MEA_JTG_FRQ_ALLFV_SI_MEAS4_1_A0_1510070021.ATP"
            // genericPatName:  "PP_MINA0_A_FULP_AN_AA03_MEA_JTG_FRQ_ALLFV_SI_MEAS4"
            string patternName = Path.GetFileName(fullPatternName);
            string[] split = patternName.Split(new[] { '_' });

            string genericPatName = "";
            for (int i = 0; i < split.Length - 3; i++)
            {
                genericPatName += split[i];
                if (i < split.Length - 4)
                { genericPatName += "_"; }
            }
            return genericPatName.ToUpper();
        }

        private string GetVersion(string fullPatternName)
        {
            try
            {


                // fullPatternName: "D:\\HardIP_Info\\miner\\PP_MINA0_A_FULP_AN_AA03_MEA_JTG_FRQ_ALLFV_SI_MEAS4_1_A0_1510070021.ATP"
                // genericPatName:  "1_A0_1510070021"
                string patternName = Path.GetFileName(fullPatternName);
                string[] split = patternName.Split(new[] { '_' });

                string versionStr = "";
                for (int i = split.Length - 3; i < split.Length; i++)
                { versionStr += split[i] + '_'; }
                versionStr = versionStr.Substring(0, versionStr.Length - 1); // remove "_"

                // remove ".ATP"
                if (versionStr.IndexOf(".", StringComparison.Ordinal) != -1)
                {
                    versionStr = versionStr.Substring(0, versionStr.IndexOf('.'));
                }

                return versionStr;
            }
            catch (Exception ex)
            {
                ErrorMessageBox.Show(string.Format(ex.ToString()));
                return "";
            }
        }

        private string GetLatestPatternVersion(Dictionary<string, string> genericPatternAllVersionInfoDict)
        {
            string latestVersion = "";
            List<string> allVersions = genericPatternAllVersionInfoDict.Keys.ToList();

            foreach (string patternVersion in allVersions)
            {
                if (latestVersion == "")
                {
                    latestVersion = patternVersion;
                    continue;
                }
                latestVersion = CompareVersion(latestVersion, patternVersion);
            }
            return latestVersion;
        }

        private string CompareVersion(string version1, string version2)
        {
            // Version1:  "1_A0_1510070021"  =>1
            // Version2:  "2_A0_1510070021"  =>2
            // 2 > 1 return Version 2

            int versionnumber1 = string.IsNullOrEmpty(version1.Split('_')[0]) ? 1 : Convert.ToInt16(version1.Split('_')[0]);
            int versionnumber2 = string.IsNullOrEmpty(version2.Split('_')[0]) ? 1 : Convert.ToInt16(version2.Split('_')[0]);
            if (versionnumber1 > versionnumber2)
            {
                return version1;
            }

            return version2;
        }
    }
}
