//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RF_PatternTool.Template.Proxima {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TempateFW {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TempateFW() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RF_PatternTool.Template.Proxima.TempateFW", typeof(TempateFW).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vm_vector body ($tset JTAG_TCK, JTAG_TDI, JTAG_TMS, JTAG_TRSTN,
        /// JTAG_TDO, JTAG_SEL, TESTMODE, CFSB, RESETN, (CTRL_GPIO_0, CTRL_GPIO_1,
        /// CTRL_GPIO_2), CLKREQ, I2C0_SDA, I2C0_SCL, TIME_SYNC, (BOOT_CFG_0, BOOT_CFG_1,
        /// BOOT_CFG_2), CCS_UART_TX, CCS_UART_RX, HOLD_RESET, (BT_GPIO_6, BT_GPIO_7),
        /// WL_DBG_UART_TX, CCS_UART_CTS, CCS_UART_RTS, PPM_ALERT, (BID0, BID1, BID2),
        /// (PMU_DVFS_0, PMU_DVFS_1), (BT_FEM_CTRL_DED_2G_0, BT_FEM_CTRL_DED_2G_1,
        /// BT_FEM_CTRL_DED_2G_2), (WLBT_FEM_CTRL_SE_0, WLBT_FEM_CTRL_SE_1,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProximaBody {
            get {
                return ResourceManager.GetString("ProximaBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srm_vector name ($tset JTAG_TCK, JTAG_TDI, JTAG_TMS, JTAG_TRSTN,
        /// JTAG_TDO, JTAG_SEL, TESTMODE, CFSB, RESETN, (CTRL_GPIO_0, CTRL_GPIO_1,
        /// CTRL_GPIO_2), CLKREQ, I2C0_SDA, I2C0_SCL, TIME_SYNC, (BOOT_CFG_0, BOOT_CFG_1,
        /// BOOT_CFG_2), CCS_UART_TX, CCS_UART_RX, HOLD_RESET, (BT_GPIO_6, BT_GPIO_7),
        /// WL_DBG_UART_TX, CCS_UART_CTS, CCS_UART_RTS, PPM_ALERT, (BID0, BID1, BID2),
        /// (PMU_DVFS_0, PMU_DVFS_1), (BT_FEM_CTRL_DED_2G_0, BT_FEM_CTRL_DED_2G_1,
        /// BT_FEM_CTRL_DED_2G_2), (WLBT_FEM_CTRL_SE_0, WLBT_FEM_CTRL_SE_1,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProximaMatchLoop {
            get {
                return ResourceManager.GetString("ProximaMatchLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; tsetJTAG 1 0 0 1 X 0 0 1 1 000 0 0 0 0 001 0 1 0 00 1 1 0 0 000 00 000 000 0000 0000 000 0000 0 00 000 0000 0 0 0 0 0 0 0 0 0 0 0 0 000000 0 00 0 0 0 0 000 0 0 0 1 0 0 0 0 0 ; // 3135 V:150 C:151 
        /// &gt; tsetJTAG 1 0 0 0 X 0 0 1 1 000 0 0 0 0 001 0 1 0 00 1 1 0 0 000 00 000 000 0000 0000 000 0000 0 00 000 0000 0 0 0 0 0 0 0 0 0 0 0 0 000000 0 00 0 0 0 0 000 0 0 0 1 0 0 0 0 0 ; // 3156 V:151 C:152 
        /// &gt; tsetJTAG 1 0 0 1 X 0 0 1 1 000 0 0 0 0 001 0 1 0 00 1 1 0 0 000 00 000 000 0000 0000 000 0000 0 00 000 0000  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProximaRead {
            get {
                return ResourceManager.GetString("ProximaRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srm_vector name  ($tset JTAG_TCK, JTAG_TDI, JTAG_TMS, JTAG_TRSTN,
        /// JTAG_TDO, JTAG_SEL, TESTMODE, CFSB, RESETN, (CTRL_GPIO_0, CTRL_GPIO_1,
        /// CTRL_GPIO_2), CLKREQ, I2C0_SDA, I2C0_SCL, TIME_SYNC, (BOOT_CFG_0, BOOT_CFG_1,
        /// BOOT_CFG_2), CCS_UART_TX, CCS_UART_RX, HOLD_RESET, (BT_GPIO_6, BT_GPIO_7),
        /// WL_DBG_UART_TX, CCS_UART_CTS, CCS_UART_RTS, PPM_ALERT, (BID0, BID1, BID2),
        /// (PMU_DVFS_0, PMU_DVFS_1), (BT_FEM_CTRL_DED_2G_0, BT_FEM_CTRL_DED_2G_1,
        /// BT_FEM_CTRL_DED_2G_2), (WLBT_FEM_CTRL_SE_0, WLBT_FEM_CTRL_SE_1,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProximaSub {
            get {
                return ResourceManager.GetString("ProximaSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; tsetJTAG 1 0 0 1 X 0 0 1 1 000 0 0 0 0 001 0 1 0 00 1 1 0 0 000 00 000 000 0000 0000 000 0000 0 00 000 0000 0 0 0 0 0 0 0 0 0 0 0 0 000000 0 00 0 0 0 0 000 0 0 0 1 0 0 0 0 0 ; // 3135 V:150 C:151 
        /// &gt; tsetJTAG 1 0 0 0 X 0 0 1 1 000 0 0 0 0 001 0 1 0 00 1 1 0 0 000 00 000 000 0000 0000 000 0000 0 00 000 0000 0 0 0 0 0 0 0 0 0 0 0 0 000000 0 00 0 0 0 0 000 0 0 0 1 0 0 0 0 0 ; // 3156 V:151 C:152 
        /// &gt; tsetJTAG 1 0 0 1 X 0 0 1 1 000 0 0 0 0 001 0 1 0 00 1 1 0 0 000 00 000 000 0000 0000 000 0000 0 00 000 0000  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProximaWrite {
            get {
                return ResourceManager.GetString("ProximaWrite", resourceCulture);
            }
        }
    }
}
