//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18444
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此原始程式碼由 xsd 版本=4.0.30319.33440 自動產生。
// 


using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

/// <remarks/>
[GeneratedCode("xsd", "4.0.30319.33440")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://tempuri.org/DiffPairConfig.xsd")]
[XmlRoot(Namespace="http://tempuri.org/DiffPairConfig.xsd", IsNullable=false)]
public partial class DiffItem {
    
    private string posField;
    
    private string negField;
    
    /// <remarks/>
    [XmlAttribute()]
    public string Pos {
        get {
            return this.posField;
        }
        set {
            this.posField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string Neg {
        get {
            return this.negField;
        }
        set {
            this.negField = value;
        }
    }
}

/// <remarks/>
[GeneratedCode("xsd", "4.0.30319.33440")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://tempuri.org/DiffPairConfig.xsd")]
[XmlRoot(Namespace="http://tempuri.org/DiffPairConfig.xsd", IsNullable=false)]
public partial class DiffPairConfig {
    
    private DiffItem[] diffPairRulesField;
    
    private DiffItem[] diffPairPinsField;
    
    /// <remarks/>
    [XmlArrayItem("DiffItem", IsNullable=false)]
    public DiffItem[] DiffPairRules {
        get {
            return this.diffPairRulesField;
        }
        set {
            this.diffPairRulesField = value;
        }
    }
    
    /// <remarks/>
    [XmlArrayItem("DiffItem", IsNullable=false)]
    public DiffItem[] DiffPairPins {
        get {
            return this.diffPairPinsField;
        }
        set {
            this.diffPairPinsField = value;
        }
    }
}
