using CommonLib.ErrorReport.Base;

namespace CommonLib.ErrorReport.ErrorCodes
{
    public static class ScanErrorType
    {
        /// <summary>Template: "The code mismatch {0} !!!"</summary>
        /// <remarks>{0} = field or row description</remarks>
        public static readonly ErrorCode E_FormatError_01 = new(
            enumErrorCategory: EnumErrorCategory.Scan,
            enumErrorBehavior: EnumErrorBehavior.Mismatch,
            enumErrorTarget: EnumErrorTarget.Format,
            code: 1,
            template: "The code mismatch {0} !!!",
            enumErrorLevel: EnumErrorLevel.Error,
            guidance: "Open the scan sheet and inspect the flagged field for formatting issues. "
                    + "Ensure all values conform to the expected format and data type.");

        /// <summary>Template: "Instance name too long(over 150), please modify instance name by PatSetName(Orange)!!!"</summary>
        public static readonly ErrorCode E_InstanceName_01 = new(
            enumErrorCategory: EnumErrorCategory.Scan,
            enumErrorBehavior: EnumErrorBehavior.RuleViolation,
            enumErrorTarget: EnumErrorTarget.Instance,
            code: 2,
            template: "Instance name too long(over 150), please modify instance name by PatSetName(Orange)!!!",
            enumErrorLevel: EnumErrorLevel.Warning,
            guidance: "Instance name generated by autogen wil be too long and cause error in run time, use PatSetName(Orange) in test plan to shorten it. ");

        /// <summary>Template: "Missing Parameter in {0}({1}) : {2}"</summary>
        /// <remarks>{0} = parameter name, {1} = ?, {2} = ?</remarks>
        public static readonly ErrorCode E_MissingParameter_01 = new(
            enumErrorCategory: EnumErrorCategory.Scan,
            enumErrorBehavior: EnumErrorBehavior.Missing,
            enumErrorTarget: EnumErrorTarget.Parameter,
            code: 3,
            template: "Missing Parameter in {0}({1}) : {2}",
            enumErrorLevel: EnumErrorLevel.Error,
            guidance: "Missing argument in C# library function, check C# library version.");

        /// <summary>Template: "The VBT function: {0} can not find in {1} library!"</summary>
        /// <remarks>{0} = module name, {1} = ?</remarks>
        public static readonly ErrorCode E_MissVbtModule_01 = new(
            enumErrorCategory: EnumErrorCategory.Scan,
            enumErrorBehavior: EnumErrorBehavior.Missing,
            enumErrorTarget: EnumErrorTarget.Module,
            code: 4,
            template: "The VBT function: {0} can not find in {1} library!",
            enumErrorLevel: EnumErrorLevel.Error,
            guidance: "Missing function in C# library, check C# library version. ");

        /// <summary>Template: "The pattern : {0} format illegal"</summary>
        /// <remarks>{0} = pattern name</remarks>
        public static readonly ErrorCode E_Pattern_01 = new(
            enumErrorCategory: EnumErrorCategory.Scan,
            enumErrorBehavior: EnumErrorBehavior.Invalid,
            enumErrorTarget: EnumErrorTarget.Pattern,
            code: 5,
            template: "The pattern : {0} format illegal",
            enumErrorLevel: EnumErrorLevel.Error,
            guidance: "Verify the pattern name follows the expected naming convention (minimum 11 underscore-separated segments). "
                    + "Check that the pattern exists and is correctly referenced in the Scan sheet.");

        /// <summary>Template: "This test can not find any time set by pattern dashboard !!!"</summary>
        public static readonly ErrorCode E_PatternTimeSet_01 = new(
            enumErrorCategory: EnumErrorCategory.Scan,
            enumErrorBehavior: EnumErrorBehavior.Missing,
            enumErrorTarget: EnumErrorTarget.Pattern,
            code: 6,
            template: "This test can not find any time set by pattern dashboard !!!",
            enumErrorLevel: EnumErrorLevel.Error,
            guidance: "Verify the time set assigned to the scan pattern in pattern dashboard. ");

        /// <summary>Template: "There are multi time set {0} by patterns !!!"</summary>
        /// <remarks>{0} = comma-separated time set list</remarks>
        public static readonly ErrorCode E_PatternTimeSet_02 = new(
            enumErrorCategory: EnumErrorCategory.Scan,
            enumErrorBehavior: EnumErrorBehavior.Duplicate,
            enumErrorTarget: EnumErrorTarget.Pattern,
            code: 7,
            template: "There are multi time set {0} by patterns !!!",
            enumErrorLevel: EnumErrorLevel.Error,
            guidance: "Multiple time set is defined in pattern dashboard for this pattern. ");

        /// <summary>Template: "TimeSet {0} does not exist is K folder"</summary>
        /// <remarks>{0} = time set name</remarks>
        public static readonly ErrorCode E_TimeSet_01 = new(
            enumErrorCategory: EnumErrorCategory.Scan,
            enumErrorBehavior: EnumErrorBehavior.Missing,
            enumErrorTarget: EnumErrorTarget.Timing,
            code: 8,
            template: "TimeSet {0} does not exist is K folder",
            enumErrorLevel: EnumErrorLevel.Error,
            guidance: "Time set missing in source folder. ");

        /// <summary>Template: "Can't get any SCAN Tset in all payload"</summary>
        public static readonly ErrorCode E_TimeSet_02 = new(
            enumErrorCategory: EnumErrorCategory.Scan,
            enumErrorBehavior: EnumErrorBehavior.Missing,
            enumErrorTarget: EnumErrorTarget.Pattern,
            code: 9,
            template: "Can't get any SCAN Tset in all payload",
            enumErrorLevel: EnumErrorLevel.Error,
            guidance: "Check the pattern dashboard for all payload patterns in this row. "
                    + "Ensure at least one pattern has a valid SCAN time set (ScanTset) defined.");

        /// <summary>Template: "DigSrc {0} in UserFunction is not defined in UF_DigSrc sheet"</summary>
        /// <remarks>{0} = function name</remarks>
        public static readonly ErrorCode E_UserFunction_01 = new(
            enumErrorCategory: EnumErrorCategory.Scan,
            enumErrorBehavior: EnumErrorBehavior.Missing,
            enumErrorTarget: EnumErrorTarget.Userfunction,
            code: 10,
            template: "DigSrc {0} in UserFunction is not defined in UF_DigSrc sheet",
            enumErrorLevel: EnumErrorLevel.Error,
            guidance: "Check if the Userfunction key is defined in Userfunction sheet.");

        /// <summary>Template: "Need to assign digital source group for digital source pattern {0}"</summary>
        /// <remarks>{0} = pattern or digital source group name</remarks>
        public static readonly ErrorCode E_UserFunction_02 = new(
            enumErrorCategory: EnumErrorCategory.Scan,
            enumErrorBehavior: EnumErrorBehavior.Missing,
            enumErrorTarget: EnumErrorTarget.Userfunction,
            code: 11,
            template: "Need to assign digital source group for digital source pattern {0}",
            enumErrorLevel: EnumErrorLevel.Error,
            guidance: "Digital source pattern need digital source group in DigSrc sheet");

        /// <summary>Template: "UserFunction format error, should be \"DigSrc:[DigSrcGroup]\""</summary>
        public static readonly ErrorCode E_UserFunction_03 = new(
            enumErrorCategory: EnumErrorCategory.Scan,
            enumErrorBehavior: EnumErrorBehavior.Invalid,
            enumErrorTarget: EnumErrorTarget.Userfunction,
            code: 12,
            template: "UserFunction format error, should be \"DigSrc:[DigSrcGroup]\"",
            enumErrorLevel: EnumErrorLevel.Error,
            guidance: "Correct the UserFunction value in the scan instance sheet. "
                    + "The value must be two colon-separated parts: 'DigSrc' and the digital source group name.");

        /// <summary>Template: "Voltage type is different in the Sub Flow column and Voltage Category column !!!"</summary>
        public static readonly ErrorCode E_VoltageType_01 = new(
            enumErrorCategory: EnumErrorCategory.Scan,
            enumErrorBehavior: EnumErrorBehavior.Mismatch,
            enumErrorTarget: EnumErrorTarget.Voltage,
            code: 13,
            template: "Voltage type is different in the Sub Flow column and Voltage Category column !!!",
            enumErrorLevel: EnumErrorLevel.Error,
            guidance: "Verify the voltage type in Sub Flow column and Voltage Category column in test plan"
                    + "Update the configuration to use a valid voltage type.");

        /// <summary>Template: "{0} can't be found the pattern in CSV !!!"</summary>
        /// <remarks>{0} = pattern name</remarks>
        public static readonly ErrorCode W_Pattern_01 = new(
            enumErrorCategory: EnumErrorCategory.Scan,
            enumErrorBehavior: EnumErrorBehavior.Missing,
            enumErrorTarget: EnumErrorTarget.Pattern,
            code: 14,
            template: "{0} can't be found the pattern in CSV !!!",
            enumErrorLevel: EnumErrorLevel.Warning,
            guidance: "Verify the pattern name against the pattern CSV dashboard. "
                    + "Ensure the pattern is listed and the name spelling is correct.");

        /// <summary>Template: "This pattern {0} is \"Dont_useInCsv\" !!!"</summary>
        /// <remarks>{0} = pattern name</remarks>
        public static readonly ErrorCode W_Pattern_02 = new(
            enumErrorCategory: EnumErrorCategory.Scan,
            enumErrorBehavior: EnumErrorBehavior.Info,
            enumErrorTarget: EnumErrorTarget.Pattern,
            code: 15,
            template: "This pattern {0} is \"Dont_useInCsv\" !!!",
            enumErrorLevel: EnumErrorLevel.Warning,
            guidance: "The pattern is intentionally excluded via the 'dont_use' flag in the CSV. "
                    + "If the pattern is needed, update its use flag in the pattern CSV dashboard.");

        /// <summary>Template: "There are no FileVersion for {0} !!!"</summary>
        /// <remarks>{0} = pattern name</remarks>
        public static readonly ErrorCode W_Pattern_03 = new(
            enumErrorCategory: EnumErrorCategory.Scan,
            enumErrorBehavior: EnumErrorBehavior.Missing,
            enumErrorTarget: EnumErrorTarget.Pattern,
            code: 16,
            template: "There are no FileVersion for {0} !!!",
            enumErrorLevel: EnumErrorLevel.Warning,
            guidance: "Check the pattern CSV dashboard for the flagged pattern. "
                    + "Ensure a valid FileVersion value is assigned to the pattern entry.");

        /// <summary>Template: "There are multi time set {0} by patterns overwrite to {1}!!!"</summary>
        /// <remarks>{0} = comma-separated time set list with override time set context, {1} = ?</remarks>
        public static readonly ErrorCode W_PatternTimeSet_01 = new(
            enumErrorCategory: EnumErrorCategory.Scan,
            enumErrorBehavior: EnumErrorBehavior.Duplicate,
            enumErrorTarget: EnumErrorTarget.Timing,
            code: 17,
            template: "There are multi time set {0} by patterns overwrite to {1}!!!",
            enumErrorLevel: EnumErrorLevel.Warning,
            guidance: "Patterns reference different time sets. The specified time set value was used as an override. "
                    + "Verify that the override time set is correct for all patterns in this row.");
    }
}
