<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TerLintAnalyzer\TerLintAnalyzer.csproj" PrivateAssets="all" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="1.9.4.205" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Castle.Core" Version="5.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonReaderLib\CommonReaderLib.csproj" />
    <ProjectReference Include="..\LogLib\LogLib.csproj" />
  </ItemGroup>

</Project>