[Automation]
TimeSetPath = H:
PatternPath = H:
BasLibraryPath = D:\ProximaW\proximaw\Module\Library
CsLibraryPath = 
TrunkHardIpPath = 
TrunkInitEnableWdPath = 
TrunkMainEndPath = 
TrunkPatSetsAllPath =
BinCutBinTablePath =
MbistBinTablePath =
TrunkAcSpecPath =
; != 0.001 will use Ceiling/Floor for T/P DC specs
PowerSupplyRes = 0.001
RecordLog = False